"""empty message

Revision ID: 84512c85a28b
Revises: a5b1111b9d05
Create Date: 2023-05-15 12:00:44.721377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84512c85a28b'
down_revision = 'a5b1111b9d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_breads', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_breads', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
